import "server-only";

import { createAppAuth } from "@octokit/auth-app";
import { Octokit } from "@octokit/rest";
import { normalizePrivateKey, readGithubAppEnv } from "@/lib/env";

export const GITHUB_API_VERSION = "2026-03-10";
export const GITHUB_ACCEPT = "application/vnd.github+json";
const DEFAULT_GITHUB_REQUEST_TIMEOUT_MS = 30_000;

function createOctokit(installationId?: number): Octokit {
  const env = readGithubAppEnv();
  const octokit = new Octokit({
    authStrategy: createAppAuth,
    auth: {
      appId: env.GITHUB_APP_ID,
      privateKey: normalizePrivateKey(env.GITHUB_PRIVATE_KEY),
      ...(installationId === undefined ? {} : { installationId }),
    },
    userAgent: "patchrail/0.1",
  });

  configureOctokit(octokit);

  return octokit;
}

function configureOctokit(octokit: Octokit): void {
  octokit.hook.before("request", (options) => {
    options.headers.accept ??= GITHUB_ACCEPT;
    options.headers["x-github-api-version"] = GITHUB_API_VERSION;
    options.request ??= {};
    options.request.signal ??= AbortSignal.timeout(DEFAULT_GITHUB_REQUEST_TIMEOUT_MS);
  });
}

/** Authenticates as the GitHub App using a short-lived JWT generated by Octokit. */
export function getAppOctokit(): Octokit {
  return createOctokit();
}

/**
 * Authenticates as an installation. Octokit creates and refreshes the short-lived
 * token in memory; Patchrail never receives or persists the token itself.
 */
export function getInstallationOctokit(installationId: number): Octokit {
  if (!Number.isSafeInteger(installationId) || installationId <= 0) {
    throw new Error("Invalid GitHub installation ID");
  }
  return createOctokit(installationId);
}

/** Uses a GitHub App user access token only for installation ownership proof. */
export function getGitHubUserOctokit(accessToken: string): Octokit {
  if (accessToken.length < 20 || /\s/.test(accessToken)) {
    throw new Error("Invalid GitHub user access token");
  }
  const octokit = new Octokit({ auth: accessToken, userAgent: "patchrail/0.1" });
  configureOctokit(octokit);
  return octokit;
}

export function getGitHubAppInstallationUrl(state: string): string {
  const { GITHUB_APP_SLUG } = readGithubAppEnv();
  const url = new URL(
    `https://github.com/apps/${encodeURIComponent(GITHUB_APP_SLUG)}/installations/new`,
  );
  url.searchParams.set("state", state);
  return url.toString();
}

export function getGitHubInstallationManagementUrl(installationId: number): string {
  if (!Number.isSafeInteger(installationId) || installationId <= 0) {
    throw new Error("Invalid GitHub installation ID");
  }
  return `https://github.com/settings/installations/${installationId}`;
}
