import type { ChangedFile, DetectedApi, ResearchSource, VerificationResult } from "@/runs/types";
import { isUpdateRequired } from "@/runs/types";

const MAX_PR_BODY_LENGTH = 60_000;

function boundedPlainText(value: string, maximum: number): string {
  const normalized = value
    .normalize("NFC")
    .replace(/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
  const bounded =
    normalized.length <= maximum ? normalized : `${normalized.slice(0, maximum - 1).trimEnd()}…`;

  // Treat all structured-result strings as text. This prevents headings, HTML,
  // links, and @mentions embedded in AI or repository metadata from taking effect.
  return bounded
    .replace(/\\/g, "\\\\")
    .replace(/([`*_\[\]<>|])/g, "\\$1")
    .replace(/@/g, "@\u200b");
}

function safeSourceUrl(value: string): string | null {
  try {
    const url = new URL(value);
    if (url.protocol !== "https:" && url.protocol !== "http:") return null;
    if (url.username || url.password) return null;
    url.hash = "";
    return url.toString().replace(/\(/g, "%28").replace(/\)/g, "%29");
  } catch {
    return null;
  }
}

function omittedLine(total: number, shown: number, noun: string): string[] {
  const omitted = total - shown;
  return omitted > 0 ? [`- ${omitted} more ${noun} available in Patchrail.`] : [];
}

export type PullRequestBodyInput = {
  summary: string;
  detectedApis: DetectedApi[];
  research: ResearchSource[];
  changedFiles: ChangedFile[];
  verification: VerificationResult;
};

declare const patchrailPullRequestBody: unique symbol;
export type PatchrailPullRequestBody = string & {
  readonly [patchrailPullRequestBody]: true;
};

/**
 * Builds a bounded PR summary exclusively from final structured run artifacts.
 * It intentionally never accepts prompts, model reasoning, source code, logs,
 * provider telemetry, token usage, cost, or reservation data.
 */
export function buildPatchrailPullRequestBody(
  input: PullRequestBodyInput,
): PatchrailPullRequestBody {
  const apiRows = input.detectedApis
    .slice(0, 30)
    .map(
      (api) =>
        `- ${boundedPlainText(api.provider, 80)} — ${boundedPlainText(api.product, 80)} (${api.status})`,
    );
  const updates = input.detectedApis.filter((api) => isUpdateRequired(api.status));
  const updateRows = updates
    .slice(0, 30)
    .map(
      (api) =>
        `- ${boundedPlainText(api.provider, 80)} — ${boundedPlainText(api.product, 80)}: ${boundedPlainText(api.conclusion, 200)}`,
    );
  const authoritativeSources = input.research.filter(
    (source) => source.authoritative && source.sourceType !== "SECONDARY_LOCATOR",
  );
  const sourceRows = authoritativeSources.slice(0, 10).map((source) => {
    const label = boundedPlainText(source.title, 120);
    const url = safeSourceUrl(source.url);
    return url ? `- [${label}](${url})` : `- ${label}`;
  });
  const fileRows = input.changedFiles
    .slice(0, 30)
    .map((file) => `- ${file.operation}: ${boundedPlainText(file.path, 300)}`);
  const commandRows = input.verification.commands
    .slice(0, 20)
    .map(
      (command) =>
        `- ${boundedPlainText(command.command, 200)} — ${command.timedOut ? "timed out" : `exit ${command.exitCode ?? "unknown"}`} (${command.durationMs} ms)`,
    );
  const limitations = input.detectedApis.filter((api) => api.status === "INSUFFICIENT_EVIDENCE");
  const limitationRows = limitations
    .slice(0, 30)
    .map(
      (api) =>
        `- ${boundedPlainText(api.provider, 80)} — ${boundedPlainText(api.product, 80)}: ${boundedPlainText(api.conclusion, 300)}`,
    );

  const sections = [
    "<!-- Generated by Patchrail from final structured run artifacts. -->",
    "## Patchrail summary",
    boundedPlainText(input.summary, 2_000) || "API integration maintenance completed.",
    "## External APIs found",
    ...(apiRows.length > 0 ? apiRows : ["- No material external APIs recorded."]),
    ...omittedLine(input.detectedApis.length, apiRows.length, "APIs"),
    "## API updates applied",
    ...(updateRows.length > 0 ? updateRows : ["- No API migrations were required."]),
    ...omittedLine(updates.length, updateRows.length, "updates"),
    "## Official sources researched",
    ...(sourceRows.length > 0 ? sourceRows : ["- No authoritative sources recorded."]),
    ...omittedLine(authoritativeSources.length, sourceRows.length, "sources"),
    "## Changed files",
    ...(fileRows.length > 0 ? fileRows : ["- No files changed."]),
    ...omittedLine(input.changedFiles.length, fileRows.length, "files"),
    "## Verification",
    `- Result: ${input.verification.status}`,
    `- Test integrity: ${input.verification.integrityPassed ? "passed" : "failed"}`,
    ...(commandRows.length > 0 ? commandRows : ["- No verification commands recorded."]),
    ...omittedLine(input.verification.commands.length, commandRows.length, "commands"),
    "## Limitations",
    ...(limitationRows.length > 0 ? limitationRows : ["- No material limitations recorded."]),
    ...omittedLine(limitations.length, limitationRows.length, "limitations"),
    "## Draft status",
    "This pull request is a draft. Patchrail never merges changes automatically.",
  ];
  const body = sections.join("\n\n");
  if (body.length > MAX_PR_BODY_LENGTH) {
    throw new Error("Generated pull request body exceeds the safe size limit");
  }
  return body as PatchrailPullRequestBody;
}
